version: '3'

services: 
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - './data:/data/db'

  yelp_camp:
    build: ./src
    image: yelp_camp
    container_name: yelp_camp
    command: 'npm start'
    ports: 
      - '3000:3000'
    depends_on: 
      - 'mongo'